### ISSUE TITLE
Local crashes when restoring: "connection doesn't exist" for web sockets

### ISSUE THREAD

**Issue by sam-goodwin** [functionless/eventual#456]
This error occurs when i reboot the local server using web sockets. Of course the connection doesn't exist - we should not crash!

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Websocket for connection 200d0388-ff8b-42c2-a913-acfcc7339ec1 does not exist.
```

**Comment by sam-goodwin** [comment]
Stack trace:
```
Error: Websocket for connection 200d0388-ff8b-42c2-a913-acfcc7339ec1 does not exist.
    at LocalSocket.send (file:///Users/samgoodwin/workspaces/eventual-service/node_modules/.pnpm/@eventual+cli@0.55.0_@types+node@18.18.0_esbuild@0.16.17_typescript@5.2.2/node_modules/@eventual/cli/src/local/web-socket-container.ts:50:13)
    at LocalWebSocketContainer.send (file:///Users/samgoodwin/workspaces/eventual-service/node_modules/.pnpm/@eventual+cli@0.55.0_@types+node@18.18.0_esbuild@0.16.17_typescript@5.2.2/node_modules/@eventual/cli/src/local/web-socket-container.ts:14:32)
    at LocalSocketClient.send (file:///Users/samgoodwin/workspaces/eventual-service/node_modules/.pnpm/@eventual+core-runtime@0.55.0/node_modules/@eventual/core-runtime/src/local/clients/socket-client.ts:13:22)
    at SocketCallExecutor.execute (file:///Users/samgoodwin/workspaces/eventual-service/node_modules/.pnpm/@eventual+core-runtime@0.55.0/node_modules/@eventual/core-runtime/src/call-executors/socket-call-executor.ts:8:55)
    at AllCallExecutor.execute (file:///Users/samgoodwin/workspaces/eventual-service/node_modules/.pnpm/@eventual+core-runtime@0.55.0/node_modules/@eventual/core-runtime/src/call-executor.ts:43:23)
    at DefaultEventualHook.executeEventualCall (file:///Users/samgoodwin/workspaces/eventual-service/node_modules/.pnpm/@eventual+core-runtime@0.55.0/node_modules/@eventual/core-runtime/src/eventual-hook.ts:49:26)
    at Object.send (file:///Users/samgoodwin/workspaces/eventual-service/node_modules/.pnpm/@eventual+core@0.55.0/node_modules/@eventual/core/src/socket/socket.ts:176:34)
    at file:///Users/samgoodwin/workspaces/eventual-service/packages/service/src/yjs/handle-rtc.ts:66:33
    at Array.map (<anonymous>)
    at Object.$default (file:///Users/samgoodwin/workspaces/eventual-service/packages/service/src/yjs/handle-rtc.ts:64:44)
```
